"""add amount_cents to transactions

Revision ID: 64b8d19eb3fb
Revises: 460d599e6129
Create Date: 2026-10-03 14:51:27.863949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b8d19eb3fb'
down_revision: Union[str, Sequence[str], None] = '460d599e6129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('amount_cents', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'amount_cents')
    # ### end Alembic commands ###
